// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcmnzvjftmdbywrjkust.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjbW56dmpmdG1kYnl3cmprdXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDU0MTAsImV4cCI6MjA2MjgyMTQxMH0.lcHneNl7SMvxf_2FbBcSUcTsKY-9HEPdTarSZacwtt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);